### ISSUE TITLE
It will throw a warn message when used with oh-my-zsh

### ISSUE THREAD

**Issue by someok** [zpm-zsh/dircolors-material#1]
The message:

> /Users/wjx/MyFolder/Develop/MyWorkspace/_config/oh-my-zsh-custom/custom/plugins/material-colors/material-colors.plugin.zsh:44: substring expression: -1 < 2

![image](https://user-images.githubusercontent.com/1523082/104024667-72882480-51fe-11eb-8f58-de05e89cd2ec.png)

**Comment by grigorii-horos** [comment]
@someok Oops... Please install this plugin https://github.com/zpm-zsh/colors and enable it before material-colors
